package vista;

import controlador.ConceptoControler;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/** Proyecto asignatura Proyectos de programación 
 *
 * @author frami
 */
public class VistaConcepto extends javax.swing.JFrame {

    ConceptoControler cc = new ConceptoControler();

    /**
     * Creates new form VistaConcepto
     */
    public VistaConcepto() {
        initComponents();
        txtId.setEditable(false);
        ConceptoControler.cargarTablaConceptoTR(tblConcepto);
        txtAreaConceptoMultiple.setEnabled(false);
        txtNombreCM.setEnabled(false);
        setTitle("Ventana para la gestión de conceptos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConcepto = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtNombreCS = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConceptoMultiple = new javax.swing.JTextArea();
        cheBoxEsComMul = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(242, 242, 242));
        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 375, 275, -1));

        tblConcepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConceptoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblConcepto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, 770, 151));

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jLabel1.setText("Nombre del Concepto Simple:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));
        jPanel1.add(txtNombreCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 300, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel3.setText("Lista de conceptos (deben ser separador por ;)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        txtAreaConceptoMultiple.setColumns(20);
        txtAreaConceptoMultiple.setRows(5);
        jScrollPane1.setViewportView(txtAreaConceptoMultiple);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 390, 130));

        cheBoxEsComMul.setText("Es concepto multiple");
        cheBoxEsComMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBoxEsComMulActionPerformed(evt);
            }
        });
        jPanel1.add(cheBoxEsComMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel6.setText("Tipo de concepto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        jLabel7.setText("Nombre del Concepto Multiple:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(txtNombreCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConceptoMouseClicked
        int selection = tblConcepto.getSelectedRow();
        String val = tblConcepto.getValueAt(selection, 3) + "";
        if (val.equals("Si")) {
            cheBoxEsComMul.setSelected(true);
            txtId.setText(tblConcepto.getValueAt(selection, 0) + "");
            txtNombreCM.setEnabled(true);
            txtAreaConceptoMultiple.setEnabled(true);
            txtNombreCS.setEnabled(false);
            txtNombreCS.setText("");
            txtNombreCM.setText(tblConcepto.getValueAt(selection, 1) + "");
            txtAreaConceptoMultiple.setText(tblConcepto.getValueAt(selection, 2).toString().replace(",", ";") + "");
        } else {
            cheBoxEsComMul.setSelected(false);
            txtId.setText(tblConcepto.getValueAt(selection, 0) + "");
            txtNombreCM.setEnabled(false);
            txtAreaConceptoMultiple.setEnabled(false);
            txtNombreCS.setEnabled(true);
            txtNombreCM.setText("");
            txtAreaConceptoMultiple.setText("");
            txtId.setText(tblConcepto.getValueAt(selection, 0) + "");
            txtNombreCS.setText(tblConcepto.getValueAt(selection, 1) + "");
        }
    }//GEN-LAST:event_tblConceptoMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        //Capturamos
        String nombreCS = txtNombreCS.getText().trim();
        String nombreCM = txtNombreCM.getText().trim();

        boolean esConceptoMultiple = false;
        String conceptosString = txtAreaConceptoMultiple.getText();
        String[] elements = conceptosString.split(";");
        // Crear un ArrayList
        ArrayList<String> arrayConceptos = new ArrayList<>();

        if (!nombreCM.isEmpty()) {
            if (cheBoxEsComMul.isSelected()) {
                esConceptoMultiple = true;
                if (!conceptosString.isEmpty()) {
                    // Agregar cada elemento al ArrayList
                    for (String element : elements) {
                        arrayConceptos.add(element.trim()); // Trim para eliminar espacios en blanco al principio o al final
                    }
//                System.out.println("Multiple");
                    cc.guardarConcepto(nombreCS, nombreCM, esConceptoMultiple, arrayConceptos);
                    cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese el o los conceptos separados por ;");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre en concepto multiple");
            }

        } else {
            esConceptoMultiple = false;
            if (!nombreCS.isEmpty()) {
//                System.out.println("Simple");
                //Guardamos
                cc.guardarConcepto(nombreCS, nombreCM, esConceptoMultiple, arrayConceptos);
                //Limpiamos
                cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre en concepto simple");
            }
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Capturamos
        String idDoc = txtId.getText().trim();
        boolean esConceptoMultiple = false;

        if (esConceptoMultiple) {
            esConceptoMultiple = true;
            if (!idDoc.isEmpty()) {
                cc.eliminarConcepto(idDoc, esConceptoMultiple);

                //Limpiamos
                cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
            }
        } else {
            esConceptoMultiple = false;
            if (!idDoc.isEmpty()) {
                cc.eliminarConcepto(idDoc, esConceptoMultiple);

                //Limpiamos
                cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
            }
        }

        //Eliminamos

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Capturamos
        String idDoc = txtId.getText().trim();

        //Capturamos
        String nombreCS = txtNombreCS.getText().trim();
        String nombreCM = txtNombreCM.getText().trim();

        boolean esConceptoMultiple = false;
        String conceptosString = txtAreaConceptoMultiple.getText();
        String[] elements = conceptosString.split(";");
        // Crear un ArrayList
        ArrayList<String> arrayConceptos = new ArrayList<>();

        if (cheBoxEsComMul.isSelected()) {
            if (!nombreCM.isEmpty()) {
                esConceptoMultiple = true;
                if (!conceptosString.isEmpty()) {
                    // Agregar cada elemento al ArrayList
                    for (String element : elements) {
                        arrayConceptos.add(element.trim()); // Trim para eliminar espacios en blanco al principio o al final
                    }
//                System.out.println("Multiple");
                    cc.actualizarConcepto(idDoc, nombreCM, esConceptoMultiple, arrayConceptos);
                    cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
                } else {
                    cc.actualizarConcepto(idDoc, nombreCM, esConceptoMultiple, arrayConceptos);
                    JOptionPane.showMessageDialog(null, "Ingrese el o los conceptos separados por ;");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre en concepto multiple");
            }

        } else {
            esConceptoMultiple = false;
            if (!nombreCS.isEmpty()) {
//                System.out.println("Simple");
                //Guardamos
                cc.actualizarConcepto(idDoc, nombreCS, esConceptoMultiple, arrayConceptos);
                //Limpiamos
                cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre en concepto simple");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cc.limpiarCampos(txtId, txtNombreCS, txtNombreCM, txtAreaConceptoMultiple, cheBoxEsComMul);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cheBoxEsComMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBoxEsComMulActionPerformed
        if (cheBoxEsComMul.isSelected()) {
            txtNombreCS.setEnabled(false);
            txtNombreCS.setText("");
            txtAreaConceptoMultiple.setEnabled(true);
            txtNombreCM.setEnabled(true);

        } else if (!cheBoxEsComMul.isSelected()) {
            txtNombreCS.setEnabled(true);
            txtAreaConceptoMultiple.setEnabled(false);
            txtAreaConceptoMultiple.setText("");
            txtNombreCM.setEnabled(false);
            txtNombreCM.setText("");
        }
    }//GEN-LAST:event_cheBoxEsComMulActionPerformed

    /** the command line arguments
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConcepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox cheBoxEsComMul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblConcepto;
    private javax.swing.JTextArea txtAreaConceptoMultiple;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreCM;
    private javax.swing.JTextField txtNombreCS;
    // End of variables declaration//GEN-END:variables
}
