package vista;

import controlador.ComponentesGeneralControler;
import controlador.PrincipalControler;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/** Proyecto asignatura Proyectos de programación 
 *
 * @author frami
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * metodo para definir el tipo de usuario
     */
    public static String tipoUser;

    /**
     * metodo para definir el id del usuario recibido
     */
    public static String idUserRecived;

    /**
     * Creates new form VistaPrincipal
     */
    VistaProveedor vp = new VistaProveedor();
    VistaLiquidacion vl = new VistaLiquidacion();
    VistaGasto vg = new VistaGasto();
    VistaServicio vs = new VistaServicio();
    VistaInmueble vi = new VistaInmueble();
    VistaVecino vv = new VistaVecino();
    VistaUsuario vu = new VistaUsuario();
    VistaConcepto vc = new VistaConcepto();
    VistaAdministrador va  = new VistaAdministrador();
    PrincipalControler pc = new PrincipalControler();
    ComponentesGeneralControler cgc = new ComponentesGeneralControler();

    /**
     * Inicializa la vista principal
     */
    public VistaPrincipal() {
        initComponents();
        cgc.confirmarSalida(this);
        setTitle("Ventana Principal");
        this.setLocationRelativeTo(null);
        pc.ocultarTodosComponentes();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                pc.componetesSegunUsuario();
                System.out.println("Id enviado: " + VistaLogin.idUser);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsalir = new javax.swing.JButton();
        lblTipoUser = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelVecino = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();
        btnVecino = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnConcepto = new javax.swing.JButton();
        btnLiquidacion = new javax.swing.JButton();
        btnGasto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnInmueble = new javax.swing.JButton();
        btnServicio = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsalir.setBackground(new java.awt.Color(0, 0, 0));
        txtsalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtsalir.setForeground(new java.awt.Color(255, 255, 255));
        txtsalir.setText("Cerrar Sesión");
        txtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalirActionPerformed(evt);
            }
        });
        getContentPane().add(txtsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 190, -1));

        lblTipoUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoUser.setText("Tipo de Usuario");
        getContentPane().add(lblTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 122, -1));

        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 32, 122, -1));

        panelVecino.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelVecino, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 130, 100));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios);

        btnAdministrador.setForeground(new java.awt.Color(242, 242, 242));
        btnAdministrador.setBorder(null);
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdministrador);

        btnVecino.setForeground(new java.awt.Color(242, 242, 242));
        btnVecino.setBorder(null);
        btnVecino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVecinoActionPerformed(evt);
            }
        });
        jPanel2.add(btnVecino);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 480, 69));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnConcepto.setText("Conceptos");
        btnConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConceptoActionPerformed(evt);
            }
        });
        jPanel3.add(btnConcepto);

        btnLiquidacion.setText("Liquidaciones");
        btnLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiquidacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnLiquidacion);

        btnGasto.setText("Gastos");
        btnGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastoActionPerformed(evt);
            }
        });
        jPanel3.add(btnGasto);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 90));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btnInmueble.setText("Inmuebles");
        btnInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInmuebleActionPerformed(evt);
            }
        });
        jPanel4.add(btnInmueble);

        btnServicio.setText("Servicios");
        btnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicioActionPerformed(evt);
            }
        });
        jPanel4.add(btnServicio);

        btnProveedor.setText("Proveedores");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel4.add(btnProveedor);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 550, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalirActionPerformed
        ManagedChannel channel = ManagedChannelBuilder.forTarget("firestore.googleapis.com:443").build();
// Usa el canal para comunicarte con el servidor
// ...
// Cierra el canal cuando hayas terminado de usarlo
        channel.shutdown();
        try {
            channel.awaitTermination(5, TimeUnit.SECONDS);
        } catch (InterruptedException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        int respuesta = JOptionPane.showOptionDialog(null, "¿Estás seguro de que deseas salir al Login?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "No"}, "No");
        if (respuesta == JOptionPane.YES_OPTION) {
            // Aquí realizas las acciones para salir al Login
            // Por ejemplo:

            if (vp.isActive() || vp.isShowing() || vp.isVisible()) {
                vp.dispose();
            }

            if (vl.isActive() || vl.isShowing() || vl.isVisible()) {
                vl.dispose();
            }

            if (vg.isActive() || vg.isShowing() || vg.isVisible()) {
                vp.dispose();
            }

            if (vs.isActive() || vs.isShowing() || vs.isVisible()) {
                vp.dispose();
            }

            if (vi.isActive() || vi.isShowing() || vi.isVisible()) {
                vi.dispose();
            }

            if (vv.isActive() || vv.isShowing() || vv.isVisible()) {
                vv.dispose();
            }

            if (vu.isActive() || vu.isShowing() || vu.isVisible()) {
                vu.dispose();
            }

            if (vc.isActive() || vc.isShowing() || vc.isVisible()) {
                vc.dispose();
            }

            if (va.isActive() || va.isShowing() || va.isVisible()) {
                va.dispose();
            }

            VistaLogin vl = new VistaLogin();
            vl.setVisible(true);
            this.dispose(); // Cierras la ventana actual
        }
    }//GEN-LAST:event_txtsalirActionPerformed

    private void btnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicioActionPerformed
        if (vs.isActive() || vs.isShowing() || vs.isVisible()) {
            vp.dispose();
        }
        vs.setVisible(true);
    }//GEN-LAST:event_btnServicioActionPerformed

    private void btnGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastoActionPerformed
        if (vg.isActive() || vg.isShowing() || vg.isVisible()) {
            vp.dispose();
        }
        vg.setVisible(true);
    }//GEN-LAST:event_btnGastoActionPerformed

    private void btnLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiquidacionActionPerformed
        if (vl.isActive() || vl.isShowing() || vl.isVisible()) {
            vl.dispose();
        }
        vl.setVisible(true);
    }//GEN-LAST:event_btnLiquidacionActionPerformed

    private void btnVecinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVecinoActionPerformed
        if (vv.isActive() || vv.isShowing() || vv.isVisible()) {
            vv.dispose();
        }
        vv.setVisible(true);

    }//GEN-LAST:event_btnVecinoActionPerformed

    private void btnInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInmuebleActionPerformed
        if (vi.isActive() || vi.isShowing() || vi.isVisible()) {
            vi.dispose();
        }
        vi.setVisible(true);
    }//GEN-LAST:event_btnInmuebleActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        if (vp.isActive() || vp.isShowing() || vp.isVisible()) {
            vp.dispose();
        }
        vp.setVisible(true);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        if (va.isActive() || va.isShowing() || va.isVisible()) {
            va.dispose();
        }
        va.setVisible(true);
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConceptoActionPerformed
        if (vc.isActive() || vc.isShowing() || vc.isVisible()) {
            vc.dispose();
        }
        vc.setVisible(true);
    }//GEN-LAST:event_btnConceptoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if (vu.isActive() || vu.isShowing() || vu.isVisible()) {
            vu.dispose();
        }
        vu.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /** the command line arguments
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdministrador;
    public static javax.swing.JButton btnConcepto;
    public static javax.swing.JButton btnGasto;
    public static javax.swing.JButton btnInmueble;
    public static javax.swing.JButton btnLiquidacion;
    public static javax.swing.JButton btnProveedor;
    public static javax.swing.JButton btnServicio;
    public static javax.swing.JButton btnUsuarios;
    public static javax.swing.JButton btnVecino;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblTipoUser;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JPanel panelVecino;
    private javax.swing.JButton txtsalir;
    // End of variables declaration//GEN-END:variables

}
