package vista;

import controlador.SuscripcionServicioControler;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/** Asignatura Proyecto de ingenieria de software
 *
 * @author frami
 */
public class VistaSuscripcionServicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaServicio
     */
    SuscripcionServicioControler ssc = new SuscripcionServicioControler();

    /**
     * inicializa la vista de suscripcion de servicio
     */
    public VistaSuscripcionServicio() {
        initComponents();
//        SuscripcionServicioControler.cargarTablaSuscripcionServicioTR(tblSuscripcionServicio);

        try {
            SuscripcionServicioControler.cargarComboServicio(cmbServicio);
            SuscripcionServicioControler.cargarComboInmueble(cmbInmueble);
            SuscripcionServicioControler.cargarComboUsuario(cmbUsuario);
        } catch (InterruptedException | ExecutionException | IOException ex) {
            Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtId.setEditable(false);
        txtId.setText("");
        setTitle("Ventana para la gestión de Suscripción Servicio");
        txtIdUsuario.setEditable(false);
        txtIdServicio.setEditable(false);
        txtIdInmueble.setEditable(false);
        txtNombreUsuario.setEditable(false);
        txtNombreServicio.setEditable(false);
        txtNombreInmueble.setEditable(false);
        ssc.ocultarComponentesAdmin();
       
        this.setLocationRelativeTo(null);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                ssc.componetesSegunUsuario();
                String tipoUser = VistaPrincipal.lblTipoUser.getText().trim();
                System.out.println("Id enviado: " + VistaLogin.idUser);
                if (tipoUser.equals("Administrador")) {
                    SuscripcionServicioControler.cargarTablaSuscripcionServicioTR(tblSuscripcionServicio);
                } else if (tipoUser.equals("Vecino")) {
                    SuscripcionServicioControler.cargarTablaSuscripcionServicioByVecinoTR(tblSuscripcionServicio,
                            VistaPrincipal.lblUsuario.getText().trim());
                }
//                    SuscripcionServicioControler.cargarComboInmuebleByUser(cmbInmueble,
//                            VistaPrincipal.lblTipoUser.getText().trim(), VistaPrincipal.lblUsuario.getText().trim());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuscripcionServicio = new javax.swing.JTable();
        panelBtns = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        panelInputsIzquierda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbServicio = new javax.swing.JComboBox<>();
        cmbInmueble = new javax.swing.JComboBox<>();
        cmbUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreServicio = new javax.swing.JTextField();
        txtNombreInmueble = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnRecargarDesplegables = new javax.swing.JButton();
        panelInputsDerecha = new javax.swing.JPanel();
        jDateAlta = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateBaja = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cheIsActiva = new javax.swing.JCheckBox();
        txtIdInmueble = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtIdServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSuscripcionServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSuscripcionServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuscripcionServicioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSuscripcionServicio);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1090, 210));

        panelBtns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelBtns.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelBtns.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        panelBtns.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelBtns.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jPanel1.add(panelBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 440, 40));

        panelInputsIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Servicio: *");
        panelInputsIzquierda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtId.setForeground(new java.awt.Color(242, 242, 242));
        txtId.setToolTipText("");
        txtId.setBorder(null);
        panelInputsIzquierda.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 150, -1));

        jLabel2.setText("Inmueble: *");
        panelInputsIzquierda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cmbServicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbServicioItemStateChanged(evt);
            }
        });
        panelInputsIzquierda.add(cmbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        cmbInmueble.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbInmuebleItemStateChanged(evt);
            }
        });
        panelInputsIzquierda.add(cmbInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 150, -1));

        cmbUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUsuarioItemStateChanged(evt);
            }
        });
        panelInputsIzquierda.add(cmbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jLabel3.setText("Usuario: *");
        panelInputsIzquierda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        panelInputsIzquierda.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, -1));

        jLabel10.setText("Nombre Usuario:");
        panelInputsIzquierda.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel11.setText("Nombre Servicio:");
        panelInputsIzquierda.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        panelInputsIzquierda.add(txtNombreServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));
        panelInputsIzquierda.add(txtNombreInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, -1));

        jLabel12.setText("Nombre Inmueble:");
        panelInputsIzquierda.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnRecargarDesplegables.setText("Recargar Desplegables");
        btnRecargarDesplegables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarDesplegablesActionPerformed(evt);
            }
        });
        panelInputsIzquierda.add(btnRecargarDesplegables, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jPanel1.add(panelInputsIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 520, 370));

        panelInputsDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelInputsDerecha.add(jDateAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 127, -1));

        jLabel4.setText("Fecha Alta: *");
        panelInputsDerecha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        panelInputsDerecha.add(jDateBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 127, -1));

        jLabel6.setText("Fecha Baja:");
        panelInputsDerecha.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        cheIsActiva.setText("Es activa *");
        cheIsActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheIsActivaActionPerformed(evt);
            }
        });
        panelInputsDerecha.add(cheIsActiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtIdInmueble.setForeground(new java.awt.Color(242, 242, 242));
        txtIdInmueble.setToolTipText("");
        txtIdInmueble.setBorder(null);
        panelInputsDerecha.add(txtIdInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, -1));

        txtIdUsuario.setForeground(new java.awt.Color(242, 242, 242));
        txtIdUsuario.setBorder(null);
        panelInputsDerecha.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        txtIdServicio.setForeground(new java.awt.Color(242, 242, 242));
        txtIdServicio.setBorder(null);
        panelInputsDerecha.add(txtIdServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, -1));

        jPanel1.add(panelInputsDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 280, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        //Capturamos
        String idUsuario = txtIdUsuario.getText().trim();
        String idServicio = txtIdServicio.getText().trim();
        String idInmueble = txtIdInmueble.getText().trim();
        /////
        String usuario = cmbUsuario.getSelectedItem().toString();
        String[] partes = usuario.split("-");
        String usuarioCortado = partes[0].trim();
        //
        String servicio = cmbServicio.getSelectedItem().toString();
        String[] partesServicio = servicio.split("-");
        String ServicioCortado = partesServicio[0].trim();
        //
        String inmueble = cmbInmueble.getSelectedItem().toString();
        String[] partesInmueble = inmueble.split("-");
        String inmuebleCortado = partesInmueble[0].trim();

        Date fechaAlta = jDateAlta.getDate();
        Date fechaBaja = jDateBaja.getDate();
        boolean isActiva = false;

        //Validamos el check
        if (cheIsActiva.isSelected()) {
            isActiva = true;
        } else {
            isActiva = false;
        }

        if (ssc.verificarSeleccionUsuario(cmbUsuario)
                && ssc.verificarSeleccionServicio(cmbServicio)
                && ssc.verificarSeleccionInmueble(cmbInmueble)) {

            //Guardamos
            ssc.guardarSuscripcionServicio(usuarioCortado, ServicioCortado,
                    inmuebleCortado, fechaAlta, fechaBaja, isActiva,
                    idUsuario, idServicio, idInmueble);
            //Limpiamos
            ssc.limpiarCampos(txtId, cmbUsuario,
                    cmbServicio, cmbInmueble,
                    jDateAlta, jDateBaja, cheIsActiva,
                    txtIdUsuario, txtIdServicio, txtIdInmueble,
                    txtNombreUsuario, txtNombreServicio, txtNombreInmueble);

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Capturamos
        String idDoc = txtId.getText().trim();

        //Eliminamos
        if (!idDoc.isEmpty()) {
            ssc.eliminarSuscripcionServicio(idDoc);
            //Limpiamos
            ssc.limpiarCampos(txtId, cmbUsuario,
                    cmbServicio, cmbInmueble,
                    jDateAlta, jDateBaja, cheIsActiva,
                    txtIdUsuario, txtIdServicio, txtIdInmueble,
                    txtNombreUsuario, txtNombreServicio, txtNombreInmueble);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Capturamos
        String idDoc = txtId.getText().trim();
        String idUsuario = txtIdUsuario.getText().trim();
        String idServicio = txtIdServicio.getText().trim();
        String idInmueble = txtIdInmueble.getText().trim();
        //Capturamos;

        /////
        String usuario = cmbUsuario.getSelectedItem().toString();
        String[] partes = usuario.split("-");
        String usuarioCortado = partes[0].trim();
        //
        String servicio = cmbServicio.getSelectedItem().toString();
        String[] partesServicio = servicio.split("-");
        String ServicioCortado = partesServicio[0].trim();
        //
        String inmueble = cmbInmueble.getSelectedItem().toString();
        String[] partesInmueble = inmueble.split("-");
        String inmuebleCortado = partesInmueble[0].trim();

        Date fechaAlta = jDateAlta.getDate();
        Date fechaBaja = jDateBaja.getDate();
        boolean isActiva = false;

        //Validamos el check
        if (cheIsActiva.isSelected()) {
            isActiva = true;
        } else {
            isActiva = false;
        }

        if (!idDoc.isEmpty()) {

            if (ssc.verificarSeleccionUsuario(cmbUsuario)
                    && ssc.verificarSeleccionServicio(cmbServicio)
                    && ssc.verificarSeleccionInmueble(cmbInmueble)) {
                if (fechaAlta != null) {
                    if (fechaBaja != null) {
                        //Guardamos
                        ssc.actualizarServicio(idDoc, usuarioCortado,
                                ServicioCortado, inmuebleCortado,
                                fechaAlta, fechaBaja,
                                isActiva, idUsuario, idServicio,
                                idInmueble);
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione la fecha de baja");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione la fecha de alta");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        ssc.limpiarCampos(txtId, cmbUsuario,
                cmbServicio, cmbInmueble,
                jDateAlta, jDateBaja, cheIsActiva,
                txtIdUsuario, txtIdServicio, txtIdInmueble,
                txtNombreUsuario, txtNombreServicio, txtNombreInmueble);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblSuscripcionServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuscripcionServicioMouseClicked
        int selection = tblSuscripcionServicio.getSelectedRow();
        txtId.setText(tblSuscripcionServicio.getValueAt(selection, 0) + "");
        txtNombreUsuario.setText(tblSuscripcionServicio.getValueAt(selection, 1) + "");
        txtNombreServicio.setText(tblSuscripcionServicio.getValueAt(selection, 2) + "");
        txtNombreInmueble.setText(tblSuscripcionServicio.getValueAt(selection, 3) + "");

        String fechaAltaString = (String) tblSuscripcionServicio.getValueAt(selection, 4);
        String fechaBajaString = (String) tblSuscripcionServicio.getValueAt(selection, 5);
        String isObligatorio = tblSuscripcionServicio.getValueAt(selection, 6) + "";
        txtIdUsuario.setText(tblSuscripcionServicio.getValueAt(selection, 7) + "");
        txtIdServicio.setText(tblSuscripcionServicio.getValueAt(selection, 8) + "");
        txtIdInmueble.setText(tblSuscripcionServicio.getValueAt(selection, 9) + "");

        if (isObligatorio.equals("Si")) {
            cheIsActiva.setSelected(true);
        } else if (isObligatorio.equals("No")) {
            cheIsActiva.setSelected(false);
        }

        // Obtener el valor de la celda de la tabla como String
// Definir el formato de fecha que se está utilizando en la tabla
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        try {
            // Convertir el String a un objeto Date utilizando el formato definido
            Date fechaAlta = dateFormat.parse(fechaAltaString);
            Date fechaBaja = dateFormat.parse(fechaBajaString);

            // Establecer la fecha en el JDateChooser
            jDateAlta.setDate(fechaAlta);
            jDateBaja.setDate(fechaBaja);
        } catch (ParseException ex) {
            // Manejar el error en caso de que el String no se pueda convertir a Date
            System.out.println("Error al convertir fecha: " + ex.getMessage());
        }

    }//GEN-LAST:event_tblSuscripcionServicioMouseClicked

    private void cmbUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUsuarioItemStateChanged
        if (cmbUsuario.getSelectedIndex() != 0) {
            String usuario = cmbUsuario.getSelectedItem().toString();
            String[] partesUsuario = usuario.split("-");
            String nombreUser = partesUsuario[0].trim();
            String idUser = partesUsuario[1].trim();
            txtNombreUsuario.setText(nombreUser);
            txtIdUsuario.setText(idUser);
        }
    }//GEN-LAST:event_cmbUsuarioItemStateChanged

    private void cmbServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbServicioItemStateChanged
        if (cmbServicio.getSelectedIndex() != 0) {
            String servicio = cmbServicio.getSelectedItem().toString();
            String[] partesServicio = servicio.split("-");
            String nombreServicio = partesServicio[0].trim();
            String idServicio = partesServicio[1].trim();
            txtNombreServicio.setText(nombreServicio);
            txtIdServicio.setText(idServicio);
        }
    }//GEN-LAST:event_cmbServicioItemStateChanged

    private void cmbInmuebleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbInmuebleItemStateChanged
        if (cmbInmueble.getSelectedIndex() != 0) {
            String inmueble = cmbInmueble.getSelectedItem().toString();
            String[] partesInmueble = inmueble.split("-");
            String nombreInmueble = partesInmueble[0].trim();
            String idInmueble = partesInmueble[1].trim();
            txtNombreInmueble.setText(nombreInmueble);
            txtIdInmueble.setText(idInmueble);
        }
    }//GEN-LAST:event_cmbInmuebleItemStateChanged

    private void btnRecargarDesplegablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarDesplegablesActionPerformed
        try {
            SuscripcionServicioControler.cargarComboServicio(cmbServicio);
            SuscripcionServicioControler.cargarComboInmueble(cmbInmueble);
            SuscripcionServicioControler.cargarComboUsuario(cmbUsuario);
        } catch (InterruptedException | ExecutionException | IOException ex) {
            Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRecargarDesplegablesActionPerformed

    private void cheIsActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheIsActivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheIsActivaActionPerformed

    /** the command line arguments
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSuscripcionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSuscripcionServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCrear;
    public static javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnLimpiar;
    public static javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRecargarDesplegables;
    private javax.swing.JCheckBox cheIsActiva;
    private javax.swing.JComboBox<String> cmbInmueble;
    private javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JComboBox<String> cmbUsuario;
    public static com.toedter.calendar.JDateChooser jDateAlta;
    public static com.toedter.calendar.JDateChooser jDateBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JPanel panelBtns;
    public static javax.swing.JPanel panelInputsDerecha;
    public static javax.swing.JPanel panelInputsIzquierda;
    private javax.swing.JTable tblSuscripcionServicio;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdInmueble;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreInmueble;
    private javax.swing.JTextField txtNombreServicio;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
