package vista;

import controlador.DetalleLiquidacionControler;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

/** Asignatura Proyecto de ingenieria de software
 *
 * @author frami
 */
public class VistaDetalleLiquidacion extends javax.swing.JFrame {

    DetalleLiquidacionControler dlc = new DetalleLiquidacionControler();

    /**
     * Creates new form VistaDetalleLiquidacion
     */
    public VistaDetalleLiquidacion() {
        initComponents();
        setTitle("Ventana de visualización de Detalles de Liquidación");
        this.setLocationRelativeTo(null);

        txtId.setEditable(false);
        dlc.ocultarFiltroVecino();

//        DetalleLiquidacionControler.cargarAllTablaDetalleLiquidacionTR(tblDetalleLiquidacion);
        try {
            DetalleLiquidacionControler.cargarComboLiquidacion(cmbPeriodoLiquidacion);
            DetalleLiquidacionControler.cargarComboServicio(cmbServicio);
            DetalleLiquidacionControler.cargarComboInmueble(cmbInmueble);
            DetalleLiquidacionControler.cargarComboVecino(cmbVecino);
        } catch (InterruptedException | ExecutionException | IOException ex) {
            Logger.getLogger(VistaDetalleLiquidacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                dlc.tablaAndFiltroVecinoSegunUsuario(tblDetalleLiquidacion);
                System.out.println("Id enviado: " + VistaLogin.idUser);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleLiquidacion = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        cmbPeriodoLiquidacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnCargarTodosDatos = new javax.swing.JButton();
        btnFiltrarByLiquidacion = new javax.swing.JButton();
        cmbServicio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnFiltrarByServicio = new javax.swing.JButton();
        btnFiltroByInmueble = new javax.swing.JButton();
        cmbInmueble = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnFiltroByVecino = new javax.swing.JButton();
        cmbVecino = new javax.swing.JComboBox<>();
        lblVecino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDetalleLiquidacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalleLiquidacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleLiquidacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetalleLiquidacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 19, 1310, 490));

        txtId.setForeground(new java.awt.Color(242, 242, 242));
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 240, -1));

        jPanel1.add(cmbPeriodoLiquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 150, 30));

        jLabel1.setText("Periodo Liquidación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        btnCargarTodosDatos.setText("Cargar Todo");
        btnCargarTodosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTodosDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarTodosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, 30));

        btnFiltrarByLiquidacion.setText("Filtrar");
        btnFiltrarByLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarByLiquidacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrarByLiquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        jPanel1.add(cmbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 150, 30));

        jLabel2.setText("Servicio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        btnFiltrarByServicio.setText("Filtrar");
        btnFiltrarByServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarByServicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrarByServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, -1, -1));

        btnFiltroByInmueble.setText("Filtrar");
        btnFiltroByInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroByInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltroByInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 620, -1, -1));

        jPanel1.add(cmbInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 150, 30));

        jLabel3.setText("Inmueble:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, -1, -1));

        btnFiltroByVecino.setText("Filtrar");
        btnFiltroByVecino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroByVecinoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltroByVecino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 620, -1, -1));

        jPanel1.add(cmbVecino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 580, 150, 30));

        lblVecino.setText("Vecino:");
        jPanel1.add(lblVecino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDetalleLiquidacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleLiquidacionMouseClicked
        int selection = tblDetalleLiquidacion.getSelectedRow();
        txtId.setText(tblDetalleLiquidacion.getValueAt(selection, 0) + "");
//        txtNombre.setText(tblDetalleLiquidacion.getValueAt(selection, 1) + "");
//
//        txtInporteTotal.setText(tblDetalleLiquidacion.getValueAt(selection, 3) + "");
//        cmbLiquidacion.setSelectedItem(tblDetalleLiquidacion.getValueAt(selection, 4) + "");
//        txtIdUser.setText(tblDetalleLiquidacion.getValueAt(selection, 5) + "");
//        txtNombreUser.setText(tblDetalleLiquidacion.getValueAt(selection, 6) + "");
    }//GEN-LAST:event_tblDetalleLiquidacionMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCargarTodosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTodosDatosActionPerformed

        dlc.tablaAndFiltroVecinoSegunUsuario(tblDetalleLiquidacion);

    }//GEN-LAST:event_btnCargarTodosDatosActionPerformed

    private void btnFiltrarByLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarByLiquidacionActionPerformed
        String periodoLiq = cmbPeriodoLiquidacion.getSelectedItem().toString();

        if (dlc.verificarSeleccionLiquidacion(cmbPeriodoLiquidacion)) {
            if (VistaPrincipal.lblTipoUser.getText().trim().equals("Administrador")) {
                dlc.cargarTablaDetalleLiquidacionTR(tblDetalleLiquidacion, periodoLiq);
            } else if (VistaPrincipal.lblTipoUser.getText().trim().equals("Vecino")) {
                dlc.cargarTablaByIdUserAndByLiquidacion(tblDetalleLiquidacion, VistaLogin.idUser, periodoLiq);
            }
        }
    }//GEN-LAST:event_btnFiltrarByLiquidacionActionPerformed

    private void btnFiltrarByServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarByServicioActionPerformed
        String servicio = cmbServicio.getSelectedItem().toString().trim();

        if (dlc.verificarSeleccionServicio(cmbServicio)) {
            if (VistaPrincipal.lblTipoUser.getText().trim().equals("Administrador")) {
                DetalleLiquidacionControler.cargarTablaServicioTR(tblDetalleLiquidacion, servicio.trim());
            } else if (VistaPrincipal.lblTipoUser.getText().trim().equals("Vecino")) {
                dlc.cargarTablaByTtlAndByServicioByServicio(tblDetalleLiquidacion, VistaLogin.idUser, servicio);
            }
        }
    }//GEN-LAST:event_btnFiltrarByServicioActionPerformed

    private void btnFiltroByInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroByInmuebleActionPerformed
        String inmueble = cmbInmueble.getSelectedItem().toString();

        if (dlc.verificarSeleccionInmueble(cmbInmueble)) {
            if (VistaPrincipal.lblTipoUser.getText().trim().equals("Administrador")) {
                dlc.cargarTablaInmuebleTR(tblDetalleLiquidacion, inmueble);
            } else if (VistaPrincipal.lblTipoUser.getText().trim().equals("Vecino")) {
                dlc.cargarTablaByIdUserAndByInmueble(tblDetalleLiquidacion, VistaLogin.idUser, inmueble);
            }
        }
    }//GEN-LAST:event_btnFiltroByInmuebleActionPerformed

    private void btnFiltroByVecinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroByVecinoActionPerformed
         String vecino = cmbVecino.getSelectedItem().toString();

        if (dlc.verificarSeleccionVecino(cmbVecino)) {
            if (VistaPrincipal.lblTipoUser.getText().trim().equals("Administrador")) {
                dlc.cargarTablaVecinoTR(tblDetalleLiquidacion, vecino);
            } else if (VistaPrincipal.lblTipoUser.getText().trim().equals("Vecino")) {
                dlc.cargarTablaByIdUserAndByVecino(tblDetalleLiquidacion, VistaLogin.idUser, vecino);
            }
        }
    }//GEN-LAST:event_btnFiltroByVecinoActionPerformed

    /** the command line arguments
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDetalleLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDetalleLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDetalleLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDetalleLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDetalleLiquidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarTodosDatos;
    private javax.swing.JButton btnFiltrarByLiquidacion;
    private javax.swing.JButton btnFiltrarByServicio;
    private javax.swing.JButton btnFiltroByInmueble;
    public static javax.swing.JButton btnFiltroByVecino;
    private javax.swing.JComboBox<String> cmbInmueble;
    private javax.swing.JComboBox<String> cmbPeriodoLiquidacion;
    private javax.swing.JComboBox<String> cmbServicio;
    public static javax.swing.JComboBox<String> cmbVecino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblVecino;
    private javax.swing.JTable tblDetalleLiquidacion;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
