package vista;

import controlador.VecinoControler;
import javax.swing.JOptionPane;

/** Asignatura Proyecto de ingenieria de software
 *
 * @author frami
 */
public class VistaVecino extends javax.swing.JFrame {

    VecinoControler vc = new VecinoControler();

    /**
     * Creates new form VistaVecino
     */
    public VistaVecino() {
        initComponents();
        VecinoControler.cargarTablaVecinoTR(tblUsuarios);
        txtId.setEditable(false);
        setTitle("Ventana para la gestión de vecinos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreAppUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtNombresUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRepPass = new javax.swing.JPasswordField();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 252, 122, -1));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 232, -1, -1));

        jLabel4.setText("Nombres");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 232, -1, -1));
        jPanel1.add(txtNombreAppUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 252, 122, -1));

        jLabel6.setText("Nombre de usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 232, -1, -1));

        txtPass.setText("....");
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 252, 122, -1));
        jPanel1.add(txtNombresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 122, -1));

        jLabel7.setText("Rep. Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 232, -1, -1));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 342, 122, -1));

        jLabel8.setText("DNI");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 322, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 342, 122, -1));

        jLabel9.setText("Teléfono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 322, -1, -1));

        txtRepPass.setText("....");
        txtRepPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRepPassMouseClicked(evt);
            }
        });
        jPanel1.add(txtRepPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 252, 122, -1));

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jLabel10.setText("Id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 20, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 216, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1000, 180));
        jPanel1.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, -1));

        jLabel11.setText("Id Usuario");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        vc.isPasswordFieldClicked(txtPass);
    }//GEN-LAST:event_txtPassMouseClicked

    private void txtRepPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRepPassMouseClicked
        vc.isPasswordFieldClicked(txtRepPass);
    }//GEN-LAST:event_txtRepPassMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String usuario = txtNombreAppUsuario.getText().trim();
        String clave = txtPass.getText().trim();
        String claveRep = txtRepPass.getText().trim();
        String dni = txtDni.getText().trim();
        String nombres = txtNombresUsuario.getText().trim();
        String email = txtEmail.getText().trim();
        String telefono = txtTelefono.getText().trim();

        if (!usuario.isEmpty()) {
            if (!usuario.isEmpty()) {
                if (!dni.isEmpty()) {
                    if (!nombres.isEmpty()) {
                        if (!email.isEmpty()) {
                            if (!telefono.isEmpty()) {
                                if (vc.validarCorreoContrasena(email, clave)) {
                                    if (vc.contraseñasIguales(clave, claveRep)) {
                                        vc.guardarVecino(usuario, clave, dni, nombres, "Vecino", telefono, email);
                                        vc.limpiarCamposAdmin(txtId, txtIdUsuario,
                                                txtNombreAppUsuario, txtPass, txtRepPass,
                                                txtNombresUsuario, txtDni, txtTelefono, txtEmail);
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese el telefono");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese el e-mail");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese los nombres");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese el DNI");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese la contraseña");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el usuario");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Capturamos
        String idDoc = txtId.getText().trim();
        String idUsuario = txtIdUsuario.getText().trim();

        //Eliminamos
        if (!idDoc.isEmpty()) {
            vc.eliminarVecino(idDoc, idUsuario);
            //Limpiamos
            vc.limpiarCamposAdmin(txtId, txtIdUsuario, 
                    txtNombreAppUsuario, txtPass, txtRepPass,
                    txtNombresUsuario, txtDni, txtTelefono, txtEmail);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String idDoc = txtId.getText().trim();
        String idUsuario = txtIdUsuario.getText().trim();
        String usuario = txtNombreAppUsuario.getText().trim();
        String clave = txtPass.getText().trim();
        String claveRep = txtRepPass.getText().trim();
        String dni = txtDni.getText().trim();
        String nombres = txtNombresUsuario.getText().trim();
        String email = txtEmail.getText().trim();
        String telefono = txtTelefono.getText().trim();

        if (!idDoc.isEmpty()) {
            if (!usuario.isEmpty()) {
                if (!usuario.isEmpty()) {
                    if (!dni.isEmpty()) {
                        if (!nombres.isEmpty()) {
                            if (!email.isEmpty()) {
                                if (!telefono.isEmpty()) {
                                    if (vc.validarCorreoContrasena(email, clave)) {
                                        if (vc.contraseñasIguales(clave, claveRep)) {
                                            vc.actualizarUsuario(idDoc, idUsuario,
                                                    usuario, clave,
                                                    dni, nombres, "Vecino", telefono, email);
                                        }
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Ingrese el telefono");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese el e-mail");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese los nombres");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese el DNI");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese la contraseña");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un ID de un dato de la tabla");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        vc.limpiarCamposAdmin(txtId, txtIdUsuario,
                txtNombreAppUsuario, txtPass, txtRepPass,
                txtNombresUsuario, txtDni, txtTelefono, txtEmail);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int selection = tblUsuarios.getSelectedRow();
        txtId.setText(tblUsuarios.getValueAt(selection, 0) + "");
        txtIdUsuario.setText(tblUsuarios.getValueAt(selection, 1) + "");
        txtNombreAppUsuario.setText(tblUsuarios.getValueAt(selection, 2) + "");
        txtPass.setText(tblUsuarios.getValueAt(selection, 3) + "");
        txtRepPass.setText(tblUsuarios.getValueAt(selection, 3) + "");
        txtDni.setText(tblUsuarios.getValueAt(selection, 4) + "");
        txtNombresUsuario.setText(tblUsuarios.getValueAt(selection, 5) + "");
        txtTelefono.setText(tblUsuarios.getValueAt(selection, 7) + "");
        txtEmail.setText(tblUsuarios.getValueAt(selection, 8) + "");
    }//GEN-LAST:event_tblUsuariosMouseClicked

    /** the command line arguments
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVecino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreAppUsuario;
    private javax.swing.JTextField txtNombresUsuario;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRepPass;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
